### ISSUE TITLE
Question about extending classes

### ISSUE THREAD

**Issue by ademait** [nwxrichardson/aconite#62]
Hi, I was playing with the simpleBPMN example provided in this repository, and tried to replicate some behaviors to my project. 

What I did was to extend the Activity class to define a Task class. This was done as:
```
@aconite.node(name="Activity", container="Lane")
class Activity extends FlowObject {
}

@aconite.node(extend="Activity",name="Task", container="Lane")
class Task extends Activity {
}
```

So if I added a Task in the example provided, there would not be any issues:
![imatge](https://github.com/user-attachments/assets/17ce4cca-bafe-407e-b9b2-8cdf53228902)

However, I tried to replicate this in my project, but, while the definition was exactly like the code above, when I instantiate a Task in my example, I get two Tasks. 
![imatge](https://github.com/user-attachments/assets/611f3a10-bc6e-4b43-bf6c-56e0a9d84466)

It seems it is the same element, but it appears duplicated. They share name and attributes, and if I delete one, the other gets deleted. Do you have any hint on why this is happening?

**Comment by nwxrichardson** [comment]
Both of them are creating a node for the task if you swap in this you will see that the two copies are from a different source.

``` java
@aconite.node(name="Activity", container="Lane", color = "blue")
class Activity extends FlowObject {
}

@aconite.node(extend="Activity",name="Task", container="Lane")
class Task extends Activity {
}
```

We considered making it so that the default behaviour would filter out any supertypes nodes, such as `Activity` in this case. But your issue is being cause by the fact that this is not how Sirius treats it, so you end up with two "copies". If you let me know the reason for wanting a task to have a separate node I can help you with the feature that you need.

**Comment by ademait** [comment]
Hi @nwxrichardson thank you for the fast reply :)

I understand. I was trying to differentiate between the different kinds of tasks. So I would  also introduce a notation for each kind.

**Comment by nwxrichardson** [comment]
Hi @ademait, are you ever going to instatiate the `Activity` by itself or will it always be a subclass?
